# Generated by Django 2.2 on 2019-04-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='direction',
            new_name='name',
        ),
    ]
