# Generated by Django 2.2 on 2019-04-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0002_auto_20190423_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='direction',
            new_name='name',
        ),
    ]
