# Generated by Django 2.1.7 on 2019-03-31 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0003_busstop_neighbour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='neighbour',
        ),
    ]
