# Generated by Django 2.2 on 2019-04-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0003_auto_20190423_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
