# Generated by Django 2.2 on 2019-04-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0004_auto_20190423_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_line', to='bushelper.Line'),
            preserve_default=False,
        ),
    ]
