# Generated by Django 2.1.7 on 2019-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0004_auto_20190331_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='neighbours',
            field=models.ManyToManyField(null=True, related_name='_busstop_neighbours_+', to='bushelper.BusStop'),
        ),
    ]
