# Generated by Django 2.2 on 2019-04-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0005_carrier_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='line',
        ),
        migrations.AddField(
            model_name='line',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bushelper.Carrier'),
            preserve_default=False,
        ),
    ]
