# Generated by Django 2.2 on 2019-04-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0006_auto_20190423_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopNeighbours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='bushelper.Carrier')),
            ],
        ),
        migrations.AlterField(
            model_name='busstop',
            name='neighbours',
            field=models.ManyToManyField(through='bushelper.BusStopNeighbours', to='bushelper.BusStop'),
        ),
        migrations.AlterField(
            model_name='line',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_line', to='bushelper.Carrier'),
        ),
        migrations.AddField(
            model_name='busstopneighbours',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='bushelper.BusStop'),
        ),
        migrations.AddField(
            model_name='busstopneighbours',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='bushelper.BusStop'),
        ),
    ]
