# Generated by Django 2.2 on 2019-04-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0007_auto_20190423_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='neighbours',
            new_name='neighbours_stops',
        ),
    ]
