# Generated by Django 2.2 on 2019-04-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0008_auto_20190423_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='neighbours_stops',
        ),
        migrations.AddField(
            model_name='busstop',
            name='neighbours',
            field=models.ManyToManyField(to='bushelper.BusStop'),
        ),
        migrations.DeleteModel(
            name='BusStopNeighbours',
        ),
    ]
