# Generated by Django 2.2 on 2019-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='http://ssl.gstatic.com/accounts/ui/avatar_2x.png', null=True, upload_to='', verbose_name='avatar'),
        ),
    ]
