# Generated by Django 2.1.4 on 2019-03-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bushelper', '0001_initial'),
        ('users', '0005_auto_20190311_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushelper.BusStop', verbose_name='bus_stop')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(through='users.Waypoint', to='bushelper.BusStop', verbose_name='favourites'),
        ),
    ]
