# Generated by Django 2.1.4 on 2019-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190311_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='label',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='l abel'),
        ),
    ]
